
---
- hosts: all
  become: true
  tasks:

  - name: install node
    shell: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'

  - name: Install stuff
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
        - git
        - python
        - python-pip
        - python-dev
        - python-mysqldb
        - build-essential
        - nodejs
        - mysql-server
        - nginx
        - unzip

  - name: Clone Rocketmap
    git:
      repo: 'https://github.com/RocketMap/RocketMap.git'
      dest: /vagrant/RocketMap

  - name: Clone PokeAlarm
    git:
      repo: 'https://github.com/RocketMap/PokeAlarm.git'
      dest: /vagrant/PokeAlarm

  - name: Wubbalubbadubdub
    unarchive:
      src: 'http://stuff.notfurprofit.org/folf06-2.zip'
      dest: /vagrant/RocketMap
      remote_src: yes
      validate_certs: False


  - name: Instal Pip Requirements
    pip:
      requirements: /vagrant/RocketMap/requirements.txt

  - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
    shell: |
      npm install -g npm
      apt-get uninstall node
      npm install -g n
      n stable
      npm install
      npm rebuild node-sass
    args:
      executable: /bin/bash

  - name: Node requirements
    npm:
      path: /vagrant/RocketMap

  - name: Make Database
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: rocketmapdb
      login_host: 0.0.0.0
      encoding: utf8mb4
      state: present

  - name: Run Database Backup
    mysql_db:
      state: import
      name: rocketmapdb
      target: /vagrant/Config/dump.sql


  - name: Ensure MySQL users are present.
    mysql_user:
      name: rocketmapuser
      host: '%'
      password: rocketmappassword
      priv: '*.*:ALL'
      state: present

  - name: Remove python-mysqldb package
    apt:
      name: python-mysqldb
      state: absent

  - name: move Rm stuff
    copy:
      src: config/input/rmInput/
      dest: /vagrant/RocketMap
      owner: root
      directory_mode: true

  - name: move Rm stuff
    copy:
      src: config/input/config.ini
      dest: /vagrant/RocketMap/config/config.ini
      owner: root

  - name: move heatmapNginx conf
    copy: src=config/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=0600

  - name: move nginx.conf
    copy: src=config/rocketmap.conf dest=/etc/nginx/conf.d/rocketmap.conf owner=root mode=0600

  - name: move rocketmap.service
    copy: src=config/webserver.conf dest=/etc/init/rocketmapserver.conf owner=root mode=0600

  - name: move rocketmap.service
    copy: src=config/scanserver.conf dest=/etc/init/scanserver.conf owner=root mode=0600

  - name: move my.cnf
    copy: src=config/my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

  - name: add cronjob
    cron:
      special_time: reboot
      job: service rocketmapserver start

  - name: add cronjob2
    cron:
      special_time: reboot
      job: service scanserver start

  - name: uninstall pogoapi
    shell: 'yes | pip uninstall pgoapi'
    args:
     chdir: /vagrant/RocketMap

  - name: teinstall pogoapi
    shell: 'pip install git+https://github.com/sebastienvercammen/pgoapi.git@2714019febe1c6f9d5073a15fcf982817b9212c5#egg=pgoapi'
    args:
     chdir: /vagrant/RocketMap

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes

  - name: restart mysql
    service: name=mysql state=restarted enabled=yes

  - name: restart rocketmapserver
    service: name=rocketmapserver state=restarted enabled=yes

  - name: restart scanserver
    service: name=scanserver state=restarted enabled=yes
