
---
- hosts: all
  become: true
  tasks:

  - name: install node
    shell: 'curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -'

  - name: Install stuff
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
        - git
        - python
        - python-pip
        - python-dev
        - python-mysqldb
        - build-essential
        - nodejs
        - mysql-server
        - nginx
        - unzip

  - name: Clone Rocketmap
    git:
      repo: 'https://github.com/RocketMap/RocketMap.git'
      dest: /vagrant/RocketMap

  - name: Instal Pip Requirements
    pip:
      requirements: /vagrant/RocketMap/requirements.txt

  - name: Run expect to wait for a successful PXE boot via out-of-band CIMC
    shell: |
      npm install -g npm
      apt-get uninstall node
      npm install -g n
      n stable
      npm install
      npm rebuild node-sass
    args:
      executable: /bin/bash

  - name: Node requirements
    npm:
      path: /vagrant/RocketMap

  - name: Make Database
    mysql_db:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      name: rocketmapdb
      login_host: 0.0.0.0
      encoding: utf8mb4
      state: present

  - name: Ensure MySQL users are present.
    mysql_user:
      name: rocketmapuser
      host: '%'
      password: rocketmappassword
      priv: '*.*:ALL'
      state: present

  - name: Remove python-mysqldb package
    apt:
      name: python-mysqldb
      state: absent

  - name: move nginx.conf
    copy: src=config/rocketmap.conf dest=/etc/nginx/conf.d/rocketmap.conf owner=root mode=0600

  - name: move rocketmap.service
    copy: src=config/webserver.conf dest=/etc/init/rocketmapserver.conf owner=root mode=0600

  - name: move my.cnf
    copy: src=config/my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes

  - name: restart mysql
    service: name=mysql state=restarted enabled=yes
